FlaskDeCero/app/__init__.py
from flask import Flask

import mysql.connector 


# db = list()
db = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='informatica.iesquevedo.es',
    port = 3333,
    user ='root', #USUARIO QUE USAMOS NOSOTROS
    password ='1asir', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='DanieloCF'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes

    app.register_blueprint(routes.rutas_usuarios)
    app.register_blueprint(routes.rutas_medidas)
    return app

FlaskDeCero/app/routes/routes.py
from flask import Blueprint, render_template, request, redirect

from app import db
from app.data.usuario_dao import usuarioDao
from app.data.medidas_dao import medidasDao

rutas_usuarios = Blueprint("routes", __name__)


@rutas_usuarios.route('/')
def index():
    return render_template('index.html')

@rutas_usuarios.route('/formulario', methods=['GET' , 'POST'])
def formusu():
    usuario_dao = usuarioDao()
   
    if request.method == 'POST':
        nombre = request.form['nombre']
        genero = request.form['genero']
        usuario_dao.insert(db,nombre,genero)
        return redirect('/test')
    return render_template('formulario.html')




@rutas_usuarios.route('/test', methods=['GET'])
def pepe():
    usuario_dao = usuarioDao()

    Usuarios = usuario_dao.select_all(db)

    return render_template('test.html',Usuarios=Usuarios)




rutas_medidas = Blueprint("med", __name__)


@rutas_medidas.route('/formedidas', methods=['GET', 'POST'])
def formmed():
    medidas_dao = medidasDao()
    if request.method == 'POST':
        id = request.form['id']
        peso_en_kg = request.form['peso_en_kg']
        altura_en_cm = request.form['altura_en_cm']
        edad = request.form['edad']
        nombre = request.form['nombre']
        medidas_dao.insert(db,id,peso_en_kg,altura_en_cm,edad,nombre)
        return redirect('/medidas')
    return render_template('formedidas.html')


@rutas_medidas.route('/medidas', methods=['GET'])
def medidas():
    medidas_dao = medidasDao()
    medidas = medidas_dao.select_all(db)
    return render_template('medidas.html',medidas=medidas)


    

FlaskDeCero/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>{% block title %}{% endblock %}</title>
    <h1>PAGINA DEDICADA AL ALMACENAMIENTO DE MEDIDAS CORPORALES</h1>
    {% endblock %}
</head>
<body>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        <footer>
            <p8>© TUPUTAMADRE 2022 - 2023</p8>
        </footer>
        {% endblock %}
    </div>
</body>
</html>

FlaskDeCero/app/templates/formedidas.html
{% extends "base.html" %}
{% block title %}NPC{% endblock %}

{% block content %}
<form action="{{ url_for('med.formmed') }}" method="post">
    <p>ID: <input type="text" name="id" /></p>
    <p>Peso (kg): <input type="text" name="peso_en_kg" /></p>
    <p>Altura (cm): <input type="text" name="altura_en_cm" /></p>
    <p>Edad: <input type="text" name="edad" /></p>
    <p>Nombre: <input type="text" name="nombre" /></p>
    <p><input type="submit" value="Enviar" /></p>
</form>
{% endblock %}


    



    

FlaskDeCero/app/templates/formulario.html
{% extends "base.html" %}
{% block title %}NPC{% endblock %}


{% block content %}
<form action="{{ url_for('routes.formusu') }}" method="post">
    <p>Nombre: <input type="text" name="nombre" /></p>
    <p>Genero: <input type="text" name="genero" /></p>
    <p><input type="submit" value="Enviar" /></p>
</form>
{% endblock %}

FlaskDeCero/app/templates/index.html
{% extends "base.html" %}
{% block title %}NPC{% endblock %}


{% block content %}
    
    <p1 class="important">Rellenar mediante formularios las medidas corporales de personas para almacenarlas en una based de datos
    y poder consultarlas posteriormente.
    </p1>
    
    
    <br><button onclick="window.location.href = 'http://127.0.0.1:5000/formulario' ;">ACCESO AL FORMULARIO</button>
    <button onclick="window.location.href = 'http://127.0.0.1:5000/test' ;">ACCESO A DATOS</button>
{% endblock %}

FlaskDeCero/app/templates/medidas.html
{% extends "base.html" %}
{% block title %}NPC{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Id</th>
            <th>Peso_en_kg</th>
            <th>Altura_en_cm</th>
            <th>Edad</th>
            <th>Nombre</th>
        </tr>
        {% for medida in medidas %}
            
        <tr>
            <td>{{ medida.id }}</td>
            <td>{{ medida.peso_en_kg}}</td>
            <td>{{ medida.altura_en_cm }}</td>
            <td>{{ medida.edad }}</td>
            <td>{{ medida.nombre }}</td>
        </tr>
            
        {% endfor %}
    </table>
    <button onclick="window.location.href = 'http://127.0.0.1:5000/formedidas' ;">AÑADIR MEDIDAS</button>
    <button onclick="window.location.href = 'http://127.0.0.1:5000' ;">VOLVER A INICIO</button>
{% endblock %}

FlaskDeCero/app/templates/test.html
{% extends "base.html" %}
{% block title %}NPC{% endblock %}


{% block content %}
  <table>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Genero</th>
    </tr>
  
    {% for Usuario in Usuarios %}
          
    <tr>
      <td>{{ Usuario.id }}</td>
      <td>{{ Usuario.nombre}}</td>
      <td>{{ Usuario.genero }}</td>
      
    </tr>
          
    {% endfor %}
  </table>
  <button onclick="window.location.href = 'http://127.0.0.1:5000/medidas' ;">ACCESO A MEDIDAS</button>
{% endblock %}